slam_toolbox:
  ros__parameters:

    # Çözücü Eklentileri (Solver Plugins)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_region_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function_type: NONE

    # ROS Çerçeveleri (Frames)
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true

    # 🚀 --- GECİKMEYİ BİTİREN Pİ OPTİMİZASYONLARI ---
    map_update_interval: 1.0    # Harita artık 5 saniyede bir değil, saniyede 1 kez yenilenecek!
    resolution: 0.05             # 5cm çözünürlük Pi işlemcisini inanılmaz rahatlatır.
    max_laser_range: 6.0         # Lidar yükünü hafifletmek için menzili 6 metreyle sınırladık.
    minimum_time_interval: 0.05
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # SLAM Genel Parametreleri
    max_num_nodes: 2500
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Korelasyon Parametreleri
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03

    # Döngü Yakalama (Loop Closure) Arama Parametreleri
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
